### ISSUE TITLE
GitHub & Government Paragraph

### ISSUE THREAD

**Issue by jaimiebutton** [bcgov/github-optimization#59]
Hello there 🦕

Can we write a short paragraph about the current adoption of GitHub in government, mainly focusing on Canadian government? We want to reassure them this is widely adopted and not a huge risk.

**Context: For slide 10**

**Comment by junminahn** [comment]
"Canadian government encourages contributors to build on ideas and prototype methods for engaging Canadians and open public policy development."

@jaimiebutton This is the entire list of government-level organizations using GitHub:
https://government.github.com/community/
