### ISSUE TITLE
One-liner about each org

### ISSUE THREAD

**Issue by jaimiebutton** [bcgov/github-optimization#60]
Can we have a one-line sentence explaining each of the orgs:

BC Gov
BC DevOps
BC Gov-Corporate

This doesn't need to be anything crazy, but I think you can explain the difference between Gov and DevOps better than I can.

**Context: For slide 9**

**Comment by junminahn** [comment]
`BC Gov:` the official GitHub organization to embrace all sorts of contributors and provide the workspace for BC Gov projects and resources.
`BC DevOps`: the space for resolving any issues and blockers under the DevOps Pathfinder initiative.
`BC Gov-Corporate`: the transitioning space to store applications that looking toward becoming public.
