### ISSUE TITLE
Meaning of Compliance Metrics

### ISSUE THREAD

**Issue by jaimiebutton** [bcgov/github-optimization#62]
For the Compliance current state, we mention a bunch of metrics:

> "In the BC Gov organization, we found that 97% of repositories contained a readme, 93% contained a license. 
> 
> However, only 41% had a CONTRIBUTING file, and 36% had a Contributors Code of Conduct file. For BC DevOps, 88% had license files, 98% had a readme, 40% had a CONTRIBUTING file, and 34% had a Contributors Code of Conduct file."

What do these signify/ what do they mean to the reader? Can we add an explanation?

**Context: Slide 23**

**Comment by jlangy** [comment]
The context for those numbers is mentioned a bit in the text to the left, saying that the policy framework requires the contributing, readme and license (should be 100% in theory), and highly recommends the code of conduct. We could contextualize it further, it is  a bit tricky though, I want to avoid being too opinionated becasue it came up in sprint review that 93% is considered a very good rate
