### ISSUE TITLE
Slide 18- common components

### ISSUE THREAD

**Issue by jlangy** [bcgov/github-optimization#77]
We can capture more information that Matt Hall was kind enough to put together for us.

I think along the lines:

# Common Components in BC Gov
Many current and prior attempts at cataloguing components have been made in the organization.
Prior to the devexchange, there was an [Api Registry](https://catalogue.data.gov.bc.ca/group/bc-government-api-registry) in the BC Data Catalogue. Platform Services has also built the website [DevHub](https://developer.gov.bc.ca) to post all the platform level tools, components, github repositories, and documentation they made as well as an area for community contributed content.

For package and image sharing, bcgov has organizations in both npm (@bcgov) as well as dockerhub (bcgovimages).

For shared servies, The Natural Resources common service showcase team built the [common services showcase](https://bcgov.github.io/common-service-showcase/)

In addition to these, there are multiple repositories in the bcgov organization aimed at creating common components, including:
	- common-services-team-library
	- sbc-common-components
	- moh-common-styles
	- common-components-catalogue

Communication channels have also been created through RocketChat, such as #common-components.

**Comment by junminahn** [comment]
@jlangy  Do we consider this list of the history of `Common Components` in BC Gov?

**Comment by jlangy** [comment]
yes, this is touching on Matt Hall's email outlining the history, but some of that carries over to the current state
